export const data = [
  {
    treeNumber: "1",
    species: "Mockernut Hickory",
    class: "AGS",
    dbh: "18",
    crownClass: "Codominant",
    logs: "1.5",
    bolts: "0",
    height: "65",
  },
  {
    treeNumber: "2",
    species: "Red Maple",
    class: "AGS",
    dbh: "13.2",
    crownClass: "Intermediate",
    logs: "1",
    bolts: "0",
    height: "55",
  },
  {
    treeNumber: "3",
    species: "Mockernut Hickory",
    class: "AGS",
    dbh: "17.9",
    crownClass: "Codominant",
    logs: "2",
    bolts: "0",
    height: "70",
  },
  {
    treeNumber: "4",
    species: "Red Maple",
    class: "AGS",
    dbh: "15",
    crownClass: "Intermediate",
    logs: "0.5",
    bolts: "0",
    height: "50",
  },
  {
    treeNumber: "5",
    species: "Scarlet Oak",
    class: "AGS",
    dbh: "32.9",
    crownClass: "Codominant",
    logs: "1",
    bolts: "0",
    height: "70",
  },
  {
    treeNumber: "6",
    species: "Mockernut Hickory",
    class: "AGS",
    dbh: "9.5",
    crownClass: "intermediate",
    logs: "0",
    bolts: "3",
    height: "45",
  },
  {
    treeNumber: "7",
    species: "Chestnut Oak",
    class: "AGS",
    dbh: "25.5",
    crownClass: "Codominant",
    logs: "1",
    bolts: "0",
    height: "75",
  },
  {
    treeNumber: "8",
    species: "Scarlet Oak",
    class: "AGS",
    dbh: "12.5",
    crownClass: "Intermediate",
    logs: "1",
    bolts: "0",
    height: "65",
  },
  {
    treeNumber: "9",
    species: "Scarlet Oak",
    class: "AGS",
    dbh: "24",
    crownClass: "Codominant",
    logs: "1.5",
    bolts: "0",
    height: "80",
  },
  {
    treeNumber: "10",
    species: "Scarlet Oak",
    class: "AGS",
    dbh: "23",
    crownClass: "Codominant",
    logs: "0.5",
    bolts: "0",
    height: "75",
  },
];
